### ISSUE TITLE
Integration with EasyAdmin

### ISSUE THREAD

**Issue by bastien70** [Kreyu/data-table-bundle#106]
Hey!

I manage to get the data to work on a page outside easyadmin, having taken care to activate Turbo-UX. It seems to work well!

But from EasyAdmin, I have an action on which I would like to test the data. I put the exact same script. I have a template that extends from the basic easyadmin template. I have my imports of everything I need, but strangely, it doesn't work here, the datatable remains fixed.

Have you ever tried using it on EasyAdmin?

From the controller :

```php
    #[Route(path: 'datatable', name: 'datatable')]
    public function datatableUx(Request $request, UserRepository $userRepository): Response
    {
        $queryBuilder = $userRepository->createQueryBuilder('user');
        $dataTable = $this->createDataTable(UserDataTableType::class, $queryBuilder);

        $dataTable->handleRequest($request);

        return $this->render('admin/sandbox/datatable.html.twig', [
            'users' => $dataTable->createView(),
        ]);
    }
```

From the template : 

```twig
{% extends '@EasyAdmin/layout.html.twig' %}

{% block content_title %}DataTable UX{% endblock %}

{% block main %}
    <div class="card">
        {{ data_table(users) }}
    </div>
{% endblock %}
```

The DashboardController has a `configureAssets` method to add webpack entries : 

```php
    public function configureAssets(): Assets
    {
        $assets = parent::configureAssets();
        $assets->addWebpackEncoreEntry('admin');

        return $assets;
    }
```

In the bootstrap.js (which will load all ux-controllers), I've added a `alert('here')` to be sure. It's okay. I'm passing in. But datatable seems to be static.

maybe with easyadmin it can't work the same way?

Here is a video demo (all lines are fake data) . Firstly from normal controller, and secondly from EasyAdmin : 

https://github.com/Kreyu/data-table-bundle/assets/53140475/d76b8e36-5236-479a-9d83-d1191d840a93

I'm wondering if, from the pagination template, if generating URL using AdminUrlGenerator from easyAdmin could solve the problem. But in this case, I should update all url generations (filters, pagination) by using easyadmin AdminUrlgenerator service 

Edit : Ok I tried to manually update the base file, for the next page url, like this : 

```twig
{% set routeParams = app.request.attributes.get('_route_params')|merge(app.request.query.all)|merge({ (page_parameter_name): current_page_number + 1 }) %}
        {% set ea_url_generator = ea_url() %}
        {% set nextPageUrl = ea_url_generator.setRoute(app.request.get('_route')).setAll(routeParams).generateUrl() %}

        {% with { path: nextPageUrl } %}
            {{ block('pagination_next', theme) }}
        {% endwith %}
```

Result is exactly the same, so, maybe it was not the problem :(

**Comment by Kreyu** [comment]
Hey @bastien70.

First, please try using the 0.18.1 if you are not using it currently, as recently there were some changes according to the turbo frame behavior in #103 (and #104 respectively).

Then, please make sure the HTML contains a turbo frame wrapped around the data table. It is included in the built-in themes, so I don't think this is it unless you removed it from your theme.

Maybe the layout you're using on the EasyAdmin-side prevents proper usage of Turbo? Something like [this meta tag](https://turbo.hotwired.dev/handbook/drive#ensuring-specific-pages-trigger-a-full-reload), or straight up something contains [`data-turbo` attribute set to false?](https://turbo.hotwired.dev/reference/attributes). Do you have any other parts of the website using Turbo? Maybe this problem is not specific to the bundle?

**Comment by bastien70** [comment]
You're right, EasyAdmin has in his layout template : 

```twig
<html lang="{{ ea.i18n.htmlLocale }}" dir="{{ ea.i18n.textDirection }}" data-turbo="false">
//...
</html>
```

By setting it to true, it works! Sorry for the issue

**Comment by Kreyu** [comment]
Great to hear! 😄 If you need help with something else related to EasyAdmin, feel free to reopen the issue.
