### ISSUE TITLE
[Persistence] URL params are not re-added to the url after leaving and reopening the table page

### ISSUE THREAD

**Issue by CMH-Benny** [Kreyu/data-table-bundle#107]
I just noticed that the persistence is not fully restoring the state, the url remains without params and even tho the filters are still applied, when you click away one of the filters it will reset all of them because the url does not match the filter state.

You can easily reproduce it:

Open a table, Search and apply one other filter and submit it.
Now leave the page and go back.
The filters seem to be still aplied, but now remove the additional filter to only keep the search
Table is now fully unfiltered

Any idea, where I might could hook in and re-add the url params properly?

**Comment by Kreyu** [comment]
Hey!

You're right, I missed that part. I am not sure how we should handle this thing properly. On the backend-side, this would require a full redirection, but keep in mind that multiple data tables can be displayed at the same time. Doing this on the frontend-side (adding URL params on render) however, would simply require reading a filtration form (we can easily create `FormData` from a filtration form and convert it to `URLSearchParams`).

Currently, I'm more inclined towards the latter option, but I'll have to think about it.

**Comment by CMH-Benny** [comment]
Wow, you're fast! :D

I think the issue is, that the clear filter "buttons" are links, if we somehow could turn them into submit buttons, that submit the form but clear their according field before the submit, it should handle it as a normal form submit again and so send the remaining restored data with it and re-add the params. It's not optmal, because you have that initial state without params, so if someone shares that url the other one might see a different view, but at least the functionaity for the specific user would just work :)

**Comment by CMH-Benny** [comment]
I really need to solve this somehow, was also thinking about not using persitence and transport the index url to other pages and use it for redirection.

From my thinking to me the only real solution would be a full redirect so the user doesn't even notice the restore step and since we have the data in backend as we restore it, it would make sense to handle it there.However i do see the problem of multiple tables on one page, if the first table is restored via redirect and it then hits the next one it would redirect an additional time and would have to somehow maintain the params of the previous one. This is really not an easy problem to solve :D

Or restore logic neds to change, it need to happen as the first step somehow and kinda needs to know what tables are on the page to restore them all on the same time and do a single redirect with all params from every table re-applied, but I really don't know. Maybe I will play around with my referer idea for now :3

**Comment by Kreyu** [comment]
Hey!

> I think the issue is, that the clear filter "buttons" are links. If we somehow could turn them into submit buttons, that submit the form but clear their according field before the submit, it should handle it as a normal form submit again. And since data is restored into the fields and we only clear the relevant one, it will send the remaining restored data with it and re-add the params automatically. It's not optimal, because you have that initial state without params, so if someone shares that url the other one might see a different view, but at least the functionality for the specific user would just work :)

This is a great suggestion. Currently, clearing the form submits every single field with empty string, so we can determine if persistence data should be loaded - to prevent a situation where the user clears all filters, and the bundle loads previous data from persistence. Switching this method to using Symfony form buttons, we can determine which button was clicked directly. I'm definitely taking notes here, however, changing to this won't be easy, so I'm adding this to backlog for future reference.

> There might be even a third option, if there was an event on persitence restore, we could take the data an add it to the current request query params, all following code will then pickup the parameters correctly and should handle it properly, wouldn't it?

There are no persistence events currently, but when data table loads data from persistence, it calls the `filter`, `paginate`, `sort` and `personalize`. methods. Therefore, if filtration data gets loaded from persistence, for data table it looks like someone simply called the `filter` method, and dispatches [`PRE_FILTER` and `POST_FILTER` events](https://data-table-bundle.swroblewski.pl/docs/features/filtering.html#events). Same for pagination, sorting, and personalization. Not sure if this will help in this case. We would have to create some sort of data collector, listen for those events and grab data we need, and in the end redirect with the necessary parameters. It looks like a lot of manual work, which I would like to prevent in the future, though.

> There is another thing that I wonder, why is it adding all filters to the url even only one is applied and all others are empty? I guess there is no good way around that, because that is how a form submit via GET works?

I am 99% sure that's how it works with GET form submission here, but I'll have to verify this.

**Comment by CMH-Benny** [comment]
> This is a great suggestion. Currently, clearing the form submits every single field with empty string, so we can determine if persistence data should be loaded - to prevent a situation where the user clears all filters, and the bundle loads previous data from persistence. Switching this method to using Symfony form buttons, we can determine which button was clicked directly. I'm definitely taking notes here, however, changing to this won't be easy, so I'm adding this to backlog for future reference.

I realised, that the pagination suffers from the same issue, I mean it works, it sets the page param correctly and restores the filters everytime, but actually it woul be preferable if the links would also hold the params of the currently active filters? I am just not sure, this is really a tough situation to solve :D 

> There are no persistence events currently, but when data table loads data from persistence, it calls the `filter`, `paginate`, `sort` and `personalize`. methods. Therefore, if filtration data gets loaded from persistence, for data table it looks like someone simply called the `filter` method, and dispatches [`PRE_FILTER` and `POST_FILTER` events](https://data-table-bundle.swroblewski.pl/docs/features/filtering.html#events). Same for pagination, sorting, and personalization. Not sure if this will help in this case. We would have to create some sort of data collector, listen for those events and grab data we need, and in the end redirect with the necessary parameters. It looks like a lot of manual work, which I would like to prevent in the future, though.

I see, but that means we can't really distinguish between a restore and a normal form submit? I mean probably that is possible via checking submis buttons, but as you said this sounds like a very complex and kinda manual solution. So I agree that this is the least favorable solution

> I am 99% sure that's how it works with GET form submission here, but I'll have to verify this.
I think it is, I investigated this and there is no way to only pass selected values with a normal GET. If the submit was via ajax and a script would collect the fields and put them in the form action URL instad it would be possible, but is another complex solution. It's not the worst thing, it only leads to very long URLs and I am not sure if there is still some kind of limit nowadays, I know that in the past there was

**Comment by Kreyu** [comment]
Okay, so I think I have a plan on how it should work.

For filter clearing buttons, we have `FilterClearUrlGeneratorInterface`, which currently generates the URL by merging filter data with the current route and query parameters:

https://github.com/Kreyu/data-table-bundle/blob/8a28be1c0b19aabe697098ba7af15dbe41a0b571/src/Filter/FilterClearUrlGenerator.php#L20-L35

If we had access to the `FiltrationData` object, it could append those filters to the URL parameters. Seems pretty simple and easy.

For column sorting, we have `ColumnSortUrlGeneratorInterface` (although I think it is not yet used in the template, oops), so we could do the same as above.

For pagination, I'm thinking of adding something like `PaginationUrlGeneratorInterface` that works exactly the same as those two above. Maybe we could even merge all of those into a single generator class - we'll see.

This leaves us with a functionality that appends the parameters to the URL during the render. I think I'll add an optional Stimulus controller that will do that without any additional redirections.

Thanks for your time and explanation. Now that I know exactly how to handle this and fix it, I will get to it as soon as possible 😄

**Comment by Kreyu** [comment]
Hey again @CMH-Benny!

I've added a Stimulus controller that adds those missing parameters to the URL, and it works flawlessly even with multiple data tables on the same page. Let me know if that works for you.

However, adding the solution on the PHP-side of the bundle (as I suggested above) is still in question. I tested it for a bit, and while it fixes the links so they contain missing parameters, and it works properly for a single data table, this still breaks when there's more than one data table on page. We would have to create URLs based on multiple data tables, and data tables have no clue about other instances present on the page.

**Comment by CMH-Benny** [comment]
> EDIT: Oops, sorry, ignore my previous response, the links are generated on the Twig side, so obviously **before** the Stimulus script is executed (I somehow overlooked it...). So while the changes introduced in #113 improves the experience by updating the URL, it doesn't fix this issue yet. Working on it.

Yes, but you could still get the data and pass it to a controller to update the URL. Fixing the links is already a great step and would be enough to resolve the issue I would guess, but if it would also restore the url params it would feel even better. It probably need to to a history state replace to adjust the URL "on the fly" to reflect the still applied filters that were restored.

Thank you so much for tackling this issue! <3

**Comment by Kreyu** [comment]
> E: Should've looked into the PR you linked, what I said is basically what you did :D
So you mean that the fixing of the URL generation is yet open to be implemented, because the controller/js fix is not fully sufficient?

Yeah, because the links used in clear filter buttons, pagination controls and sortable column headers are generated in the backend (in Twig), so before the javascript is executed. It makes the URLs more "shareable" (since you can just copy-paste it as the missing parameters are automatically added), but that's not enough 😄 I'll try to fix it completely by the end of this week.

Cheers

**Comment by Kreyu** [comment]
Fixed in version 0.21. If there are problems with the change, please let me know, I'll reopen this issue.
