### ISSUE TITLE
[Pagination] Adjustable Page Size

### ISSUE THREAD

**Issue by CMH-Benny** [Kreyu/data-table-bundle#122]
Hey, I've seen that the default page size is 25 and can be changed on every table via configuration:

```php
$builder->setDefaultPaginationData(new PaginationData(
    page: 1,
    perPage: 25,
));
```

Especially since it's also in the URL there might be a way to allow us to change the page size the user wants?
Maybe we can pass multiple Numbers there, like 10/25/50/100 and allow the user to choose from those allowed page sizes? 

There might also be a global setting in the yaml file to apply those numbers globally to every table automatically if not set manually as well? 

I think this could be a low hanging fruit and is a very common feature databales provide. It might some kind of dropdown near the counter of the elements in the bottom line, WDYT?

Thanks in advance!

**Comment by Kreyu** [comment]
Hey! Thanks for the suggestion. 

It should be easy to implement, as everything is already working, but there's no selector available to the user in built-in themes. However, I'll close this issue in favor of #51

**Comment by CMH-Benny** [comment]
Oh, I didn't see the other issue, totally fine to keep only one 👍 
Thank you! <3
