### ISSUE TITLE
Batch Stimulus

### ISSUE THREAD

**Issue by xDeSwa** [Kreyu/data-table-bundle#132]
Hello,

First of all, I installed it in my own project to test the batch operations (SelectAll) but it failed. Stimulus batch.js could not connect. I installed Symfony 6.4 Fresh but the same problem continued there.

![resim](https://github.com/user-attachments/assets/7c2abbb4-a73e-47c7-9b99-98d3f411158a)

```
 <div data-controller="kreyu--data-table-bundle--batch">
    {{ data_table(products, { title: 'Products' }) }}
 </div>
```

If I manually wrap it with a div and write 'kreyu--data-table-bundle--batch' to the data-controller, the connect with batch and the selectAll functions work. I checked many times to see if I made a mistake somewhere, but I couldn't find it. Thanks

**Comment by Kreyu** [comment]
Hey @xDeSwa. 

The built-in themes add `kreyu--data-table-bundle--batch` controller only for the data tables that contain at least one batch action:

https://github.com/Kreyu/data-table-bundle/blob/6324bdddda8af31b185cebcd5765ec65e2b24ef6/src/Resources/views/themes/base.html.twig#L6-L16

Are you sure your data table has at least one batch action, added by the `->addBatchAction()`?

On the other hand, I'm not sure whether the base theme support showing batch actions - I'll have to verify this, but the Stimulus controller should be applied just fine.

**Comment by xDeSwa** [comment]
hm, i added 

`$builder->addBatchAction('delete', ButtonActionType::class, [
        'href' => "testurl",
        ]);`

now connected stimulus batch.

Your project is going very well, congratulations.
