### ISSUE TITLE
Duplicated Doctrine queries since v0.24.1

### ISSUE THREAD

**Issue by maciazek** [Kreyu/data-table-bundle#140]
Hello Kreyu,
First of all: great kudos to you for this bundle, it already works really good :)

I would like to report that since v0.24.1 Doctrine queries are executed twice if Profiler is enabled. In v0.24.0 this problem doesn't occur. I'm using Symfony 6.4 and PHP 8.2.
![Zrzut ekranu z 2024-10-23 21-04-14](https://github.com/user-attachments/assets/55dbe6ba-5ef2-4882-a62f-ea8ed16c3e15)

**Comment by Kreyu** [comment]
Hey! Thank you for your kind words, and thank you for a report - I'll look into it

**Comment by maciazek** [comment]
Thank you. Just to clarify: previously I wrote "when profiler is enabled", but it looks like this problem occurs specifically in debug mode (when APP_DEBUG=1), regardless of whether the profiler is explicitly enabled or disabled in web_profiler.yaml.

Probably related to this, because it seems to be introduced in v0.24.1 too: when exporting data from all pages in debug mode, it exports current page only. If debug mode is disabled, export is correct.

**Comment by Kreyu** [comment]
Both duplicate queries and export issues should be fixed in version 0.25.0

**Comment by maciazek** [comment]
After upgrade, export always returns current page only. But I've noticed that if I change line https://github.com/Kreyu/data-table-bundle/blob/3309470fba9904784d01c1905082fd7deb1ccca0/src/DataTable.php#L587 from $this->paginate... to $dataTable->paginate... then export works as intended.

Also profiler still shows duplicated queries, but there's a difference in queries if filters are used (in example below table is limited to 5 rows per page)

**v0.24.3:**
![Screenshot 2024-11-07 at 10-16-09 Symfony Profiler](https://github.com/user-attachments/assets/782febe4-554c-4f1f-8969-da888cbd2fa6)

**v0.25.0:**
![Screenshot 2024-11-07 at 10-16-18 Symfony Profiler](https://github.com/user-attachments/assets/a4bf30d4-1207-4818-a715-2ffb1b3773bd)

And now profiler throws an error when trying to open Data Tables tab:
Neither the property "total_count" nor one of the methods "total_count()", "gettotal_count()"/"istotal_count()"/"hastotal_count()" or "__call()" exist and have public access in class "Symfony\Component\VarDumper\Cloner\Data".

**Comment by maciazek** [comment]
Checked on v0.25.2 - looks good to me, there are no duplicated queries. On very simple table I see only 2 queries, which is even better; three queries are showing only when I'm using JOINs.
Thank you very much for fixing these issues, now DataTableBundle covers all my tables' needs :) Cheers!

**Comment by Kreyu** [comment]
Great to hear, thanks for the feedback!
