### ISSUE TITLE
Items per page change not working with Turbo

### ISSUE THREAD

**Issue by davidromani** [Kreyu/data-table-bundle#153]
Since `{% block kreyu_data_table %}` is adding a `<turbo-frame>` wrapper, it seems that when you change the items per page selected amount is doing a full page reload (instead of an asynchronous call to replace only the turbo frame content).

Is this situation considered as a bug? And can be fixed?

**Comment by Kreyu** [comment]
Hey!

By default, the per-page selector is rendered with the `onchange="this.form.submit()"` attribute. I think this is not working properly with Turbo, but based on the https://stackoverflow.com/a/69537709 - probably changing it to `this.form.requestSubmit()` will work just fine. I'll check it.

**Comment by Kreyu** [comment]
Fixed in v0.25.7. 

The per-page `form` now contains new data attribute `data-turbo-frame="_self"` and its `select` control has `onchange="this.form.requestSubmit()"` data attribute. This makes the form submission asynchronous with Turbo.

Thanks for the report!

**Comment by Kreyu** [comment]
FYI: I've found another issue with the items per page selector & Turbo - the url query parameter is not updating upon submit. Will fix that in #158
