### ISSUE TITLE
Translation domain in base.html.twig

### ISSUE THREAD

**Issue by Narthall** [Kreyu/data-table-bundle#159]
Hi and thanks for the great work, the Bundle looks very promising!

Today I encountered a problem with it: whenever trying to display a data table, I ran into the following error, even with the simplest setup: `EmptyNode cannot have children`

After some investigating, it looks like the problem stems from the base.html.twig template, where, on line 218, the `trans` transformer has no parameter:

```twig
{% block pagination_per_page_message 'Items per page'|trans %}
```

I did not really have much time to look into it, so my temporary solution has been to just remove `|trans` from this line.

I'm just signalling it here so that you're also aware of it, and if I don't have the time to look into it and open a PR soon, maybe someone else can? Or maybe I did something wrong in the setup on my end?

**Comment by Kreyu** [comment]
Hey @Narthall, thanks for the report. Never seen that before, but I'll try to reproduce it.

> After some investigating, it looks like the problem stems from the base.html.twig template, where, on line 218, the trans transformer has no parameter:

The `trans` does not require additional parameters - in this case we are just piping the `Items per page` string as the first argument. Translation parameters and domain are optional (although domain is set by `trans_default_domain` on top of the template).

The error stack trace indicated that this line was causing the issue?

**Comment by Kreyu** [comment]
I've tried multiple cases and couldn't reproduce it. Disabling the translator works fine as well.

I noticed similar error somewhat related with the Symfony TwigBridge: https://github.com/twigphp/Twig/issues/4480

I'm working on Symfony 6.4 LTS, and looking at the issue above, this error was present in 7.2 (I think?). Please try updating if you're using it.

Thanks!

**Comment by Narthall** [comment]
Hey, many thanks for your answer. It seems that indeed, going from Symfony 7.1 to 7.2.1 fixed my problem.

Have a great day!
