### ISSUE TITLE
Feature request: allow user to set page size

### ISSUE THREAD

**Issue by steveWinter** [Kreyu/data-table-bundle#51]
In the SasS product we're working on some clients have quite large data sets so we want to be able to offer them the ability to select the number of records which are displayed per page. As far as I can tell this can only be set in the table builder configuration and there's no UI to allow end users to change that.

**Comment by Kreyu** [comment]
Available in the 0.23 version of the bundle. Usage explained in [the documentation](https://data-table-bundle.swroblewski.pl/docs/features/pagination.html#configuring-items-per-page).
