### ISSUE TITLE
Integration with Api Platform

### ISSUE THREAD

**Issue by Urmuz** [Kreyu/data-table-bundle#52]
Good afternoon. Make documentation on integrating tables with API Platforms. I think a lot of people will need it. Thank you

**Comment by Kreyu** [comment]
Hey! What do you have in mind? Displaying data tables using an API as remote data source, instead of retrieving data directly from the database? Cheers.

**Comment by Kreyu** [comment]
I am closing this issue, as no additional information has been provided. If you have any questions, feel free to reopen this issue.

For reference - integration with remote data sources can be handles in many ways. In most complicated cases, it is possible to [create a custom proxy query](https://data-table-bundle.swroblewski.pl/docs/features/extensibility.html#proxy-queries) (which works as an "adapter" for various data providers). If you're looking for something basic, like displaying a data table based on a simple array, then see #63.

Cheers!
