### ISSUE TITLE
Table Paginator shows double the expected results on the final page

### ISSUE THREAD

**Issue by kris-sum** [Kreyu/data-table-bundle#77]
Something's up with the pagination code, I think something in DoctrineOrmResultSetFactory 's getPaginatorItems isn't quite right:

Worked basic example:

    // controller
    $table = $this->createDataTable(
      TestTableType::class,
      $repo->getTestQuery(),
    );
    $table->handleRequest($request);
    
    return $this->render('test.html.twig', [
      'table' => $table->createView(),
    ]);

    // repository
    public function getTestQuery(): QueryBuilder
    {
        $qb = $this->createQueryBuilder('entity');
        return $qb;
    }

    // table
    class TestTableType extends AbstractDataTableType
    {
        public function buildDataTable(DataTableBuilderInterface $builder, array $options): void
        {
            $builder
                ->setDefaultPaginationData(new PaginationData(
                    page: 1,
                    perPage: 10,
                ))
                ->addColumn('moduleCode', TextColumnType::class, [
                    'sort' => true,
                ]);
        }
    }

/test?page_test_table=1
Correctly shows number of pages and item count
![image](https://github.com/Kreyu/data-table-bundle/assets/2246940/a9736019-a86e-41ec-b784-907618522143)

Penultimate page `/test?page_test_table=31` shows correctly too
![image](https://github.com/Kreyu/data-table-bundle/assets/2246940/39fc5104-5402-4247-9e4f-e695928ffb3c)

**Last page `/test?page_test_table=32` returns too many results**
![image](https://github.com/Kreyu/data-table-bundle/assets/2246940/13d9beb0-fc6d-4163-a975-6f570664f80c)

Doctrine shows **a second query** being run on the last page: 
![image](https://github.com/Kreyu/data-table-bundle/assets/2246940/ce9ff105-9eb1-4622-9e23-e785e64aa7e7)

**Comment by Kreyu** [comment]
Thanks for the bug report! I noticed this issue in one of my projects yesterday, but had no time to debug it properly. I think you're right, the result set factory seems to be the cause. I'll try to fix it asap when I'm on my work computer tomorrow :)

**Comment by kris-sum** [comment]
Thanks for the update :) I would've worked on a fix + PR if I had more time to investigate!

**Comment by Kreyu** [comment]
Hey @kris-sum, this issue should be fixed in the [0.17.11](https://github.com/Kreyu/data-table-bundle/releases/tag/v0.17.11) version, can you please confirm it is working in your project?

**Comment by kris-sum** [comment]
Looks great! Thank you for the speedy response
